[package]
name = "platform-api"
version = "0.0.1"
edition = "2021"
authors = ["Scuffle <opensource@scuffle.tv>"]
description = "Scuffle API server"

[dependencies]
anyhow = "1.0.75"
tracing = "0.1.37"
tokio = { version = "1.32.0", features = ["full"] }
serde = { version = "1.0.188", features = ["derive"] }
hyper = { version = "0.14.27", features = ["full"] }
common = { workspace = true }
sqlx = { version = "0.7.1", features = ["postgres", "runtime-tokio-native-tls", "json", "chrono", "uuid"] }
routerify = "3.0.0"
serde_json = "1.0.107"
reqwest = { version = "0.11.20", features = ["json"] }
chrono = { version = "0.4.31", default-features = false, features = ["serde", "clock"] }
async-graphql = { version = "6.0.7", features = ["apollo_tracing", "apollo_persisted_queries", "tracing", "opentelemetry", "dataloader", "string_number", "uuid"] }
hyper-tungstenite = "0.11.1"
async-stream = "0.3.5"
futures = "0.3.28"
futures-util = "0.3.28"
arc-swap = "1.6.0"
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.7"
negative-impl  = "0.1.4"
tonic = { version = "0.10.1", features = ["tls"] }
prost = "0.12.1"
uuid = "1.4.1"
bitmask-enum = "2.2.2"
argon2 = "0.5.2"
email_address = "0.2.4"
rand = "0.8.5"
lapin = { version = "2.3.1", features = ["native-tls"] }
tokio-stream = { version = "0.1.14", features = ["sync"] }
fred = { version = "6.3.2", features = ["enable-native-tls", "sentinel-client", "sentinel-auth", "subscriber-client"] }

config = { workspace = true }
pb = { workspace = true }

[dev-dependencies]
tempfile = "3.8.0"
dotenvy = "0.15.7"
http = "0.2.9"
tokio-tungstenite = "0.20.1"
portpicker = "0.1.1"
serial_test = "2.0.0"
