[package]
name = "mp4"
version = "0.0.1"
edition = "2021"

[dependencies]
byteorder = "1"
bytes = "1"
fixed = "1"
casey = "0"
paste = "1"

bytesio = { path = "../../bytesio/" }
h264 = { path = "../../codec/h264" }
h265 = { path = "../../codec/h265" }
av1 = { path = "../../codec/av1" }

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
