[package]
name = "aac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
byteorder = "1"
num-traits = "0"
num-derive = "0"
bytesio = { path = "../../bytesio" }
