[package]
name = "ingest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
tracing = "0"
native-tls = "0"
tokio-native-tls = "0"
async-trait = "0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
hyper = { version = "0", features = ["full"] }
tonic = { version = "0", features = ["tls"] }
prost = "0"
bytes = "1"
futures = "0"
futures-util = "0"
chrono = { version = "0", default-features = false, features = ["clock"] }
serde_json = "1"
uuid = "1"
async-stream = "0"
pnet = "0"
lapin = { version = "2.0.3", features = ["native-tls"] }
tokio-executor-trait = "2"
tokio-reactor-trait = "1"

common = { path = "../../common" }
rtmp = { path = "../protocol/rtmp" }
bytesio = { path = "../bytesio" }
flv = { path = "../container/flv" }
transmuxer = { path = "../transmuxer" }
mp4 = { path = "../container/mp4" }
aac = { path = "../codec/aac" }

[dev-dependencies]
dotenvy = "0"
portpicker = "0"
serial_test = "2"
tempfile = "3"

[build-dependencies]
tonic-build = "0"
prost-build = "0"
